name: Image Build, Push image and deploy in Prod env.

on:
  push:
    branches:
      - master

env: 
  DOCKER_REPO: akshaypandhare
  DOCKER_APP: demo-app
  DOCKER_APP_REPLICA: 2

jobs:

  job-4:
    name: "Prod-Deploy"
    runs-on: [self-hosted, linux]
    steps:
      - name: Check if Docker service running or not.
        continue-on-error: true
        run: |
          docker service ls | grep -w ${{ env.DOCKER_APP }}
          if [[ $? == 0 ]]; then echo "service=update" >> "$GITHUB_ENV"; else echo "service=create" >> "$GITHUB_ENV" ; fi
      - name: Deploy demo application in docker swarm service.
        run: |
          if [[ ${{ env.service }} == 0 ]]; then echo update; else echo create ; fi
