name: Image Build, Push image and deploy in Prod env.

on:
  push:
    branches:
      - main
    paths-ignore:
      #- '**/README.md'
      #- '**/cicd.yaml'
jobs:

  job-1:
    name: "Test"
    runs-on: [self-hosted, linux]
    steps:  
      - name: "Checkout Repo"
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 0

      - name: Testing python code
        run: |
              python3 ./tests/test.py

  job-2:
    name: "Build"
    needs: job-1
    runs-on: [self-hosted, linux]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: akshaypandhare
          password: Akshay@123

      - name: Docker Build and Tag repo
        run: |
              docker build -t akshaypandhare:${GITHUB_SHA::8} .
              docker push akshaypandhare:${GITHUB_SHA::8}

  job-3:
    needs: [job-1, job-2]
    name: "Prod-Deploy"
    runs-on: [self-hosted, linux]
    steps:
      - name: Deploy demo application in docker swarm service.
        run: |
          docker service create --name demo-app --replicas=2 --env-file .env --publish published=80,target=8000 akshaypandhare:${GITHUB_SHA::8}
          if [[ $? == 1 ]]; then docker service update demo-app --image akshaypandhare:${GITHUB_SHA::8} ; else echo "application deployed" ; fi
